import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/About.module.scss";

export const getStaticProps = () => {
  //we can call api here
  return {
    props: { footerstatus: true },
  };
};

const About = (props) => {
  return (
    <>
      <Head>
        <title>Next About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-info">
        <h2 className={styles.about_text}>This is about page.</h2>
        {/* <img src="/1200px-Nextjs-logo.svg.png"></img> */}
        <Image
          src="/1200px-Nextjs-logo.svg.png"
          width={100}
          height={100}
          alt="about"
        ></Image>
      </div>
    </>
  );
};

export default About;
